### ISSUE TITLE
Countries with multiple area codes are restricted to a single area code

### ISSUE THREAD

**Issue by SpencerKaiser** [necessarylion/country-list-with-dial-code-and-flag#21]
Countries like the Dominican Republic and Jamaica have several `area codes` but the library has chosen one of several and forced it... can we either get additional countries added for the variety of area codes OR (preferably) remove the area code either entirely or remove the area code when there are multiple for a given country?

Full list of country codes can be found here with area codes being broken out into parentheses when applicable:
https://en.wikipedia.org/wiki/List_of_country_calling_codes 

<img width="308" alt="image" src="https://user-images.githubusercontent.com/6445731/230498908-a86084fa-a174-4f53-aa83-6fb82c0bca7d.png">
<img width="420" alt="image" src="https://user-images.githubusercontent.com/6445731/230498962-643c8a67-872f-46d1-9017-a090c80750a9.png">

**Comment by necessarylion** [comment]
```
 { name: 'Jamaica', dial_code: '+1876', code: 'JM', flag: '🇯🇲' },
 { name: 'Jamaica', dial_code: '+1658', code: 'JM', flag: '🇯🇲' }, 

```
or 

```
 { name: 'Jamaica', dial_code: '+1876', dial_codes: ['+1876', '+1658'], code: 'JM', flag: '🇯🇲' },

```

Which one do you think is better?

**Comment by SpencerKaiser** [comment]
Honestly I think I would prefer the flexibility of knowing what's an area code vs what's a country code, so something like this would be my preferred option, but the second is definitely better IMO; first is simpler to use but has way too much data overlap

```json
 { name: 'Jamaica', dial_code: '+1', area_codes: ['876', '658'], code: 'JM', flag: '🇯🇲' },
```

**Comment by necessarylion** [comment]
> Honestly I think I would prefer the flexibility of knowing what's an area code vs what's a country code, so something like this would be my preferred option, but the second is definitely better IMO; first is simpler to use but has way too much data overlap
> 
> ```js
>  { name: 'Jamaica', dial_code: '+1', area_codes: ['876', '658'], code: 'JM', flag: '🇯🇲' },
> ```

It is very nice suggestion. 
But This plugin is more about `dial code` which is `country code` + `area code` together.
In your case, it is `country code` and `area codes`. 

And if someone want to show list on available dial codes, then he have loop again with area codes. 
So I think we better stick with this solution.

``` 
{ name: 'Jamaica', dial_code: '+1876', code: 'JM', flag: '🇯🇲' },
{ name: 'Jamaica', dial_code: '+1658', code: 'JM', flag: '🇯🇲' }, 
```

**Comment by SpencerKaiser** [comment]
I think that's totally fine, but it'd still be a great addition to have the country code split out as a separate element. If I don't want `Jamaica` showing twice, I have no real options because I don't know how to split the country code from the area code. At some point in the future, adding `country_code` in addition to `dial_code` would be great, even if the country code is redundant on the dial code field.
