### ISSUE TITLE
Random flags

### ISSUE THREAD

**Issue by Raghavj2000** [necessarylion/country-list-with-dial-code-and-flag#30]
When i search for a flag still random flag appears
![Screenshot 2023-06-28 145619](https://github.com/necessarylion/country-list-with-dial-code-and-flag/assets/89856193/55b81752-fefd-4850-b5fa-9116c9dd36e3)

**Comment by necessarylion** [comment]
Can you provide the code you used to search?

**Comment by Raghavj2000** [comment]
const selectCountry = (country) => {
    setSelectedCountry(country);
    setIsOpen(false);
    setPhoneNumber(country.dialCode);
  };

  const renderCountryFlags = () => {
    const filteredCountries = countries.filter((country) =>
      country.name.toLowerCase().includes(searchQuery.toLowerCase())
    );
  
    const sortedCountries = filteredCountries.sort((a, b) => {
      const aIndex = a.name.toLowerCase().indexOf(searchQuery.toLowerCase());
      const bIndex = b.name.toLowerCase().indexOf(searchQuery.toLowerCase());
  
      // Sort by the index of the search query in the country name
      if (aIndex < bIndex) return -1;
      if (aIndex > bIndex) return 1;
      // If the index is the same, sort by the length of the country name
      if (a.name.length < b.name.length) return -1;
      if (a.name.length > b.name.length) return 1;
      return 0;
    });
  
    const findByKeyword = (keyword) => {
      return sortedCountries.filter(
        (country) =>
          country.name.toLowerCase().includes(keyword.toLowerCase()) ||
          country.code.toLowerCase().includes(keyword.toLowerCase())
      );
    };
  
    const foundCountries = findByKeyword(searchQuery);
  
    return foundCountries.map((country) => {
      const flagSvg = CountryFlagSvg[country.code];
      const flagString = flagSvg && flagSvg.toString();

**Comment by Raghavj2000** [comment]
the problem is if i search India, all country that has letter I or letter N or A appears.

**Comment by necessarylion** [comment]
```ts
import CountryList from 'country-list-with-dial-code-and-flag'

CountryList.findByKeyword('india')
```
