### ISSUE TITLE
Adding `territory_of` to external territories

### ISSUE THREAD

**Issue by Skarvion** [necessarylion/country-list-with-dial-code-and-flag#45]
Thanks for this helpful package!

I have a suggestion to the data collected. I think in most cases, we want to only show globally recognised countries excluding external territories, such as Heard Island, Christmas Island, and etc.

Instead of having a boolean flag that only checks whether these are territories or not, I suggest to add a new flag `territory_of` that points to the code of owning country. Such as Christmas Island is a `territory_of: AU`.

With this, I can filter out entries that has this flag if I only want to get nations. This will also have an added benefit that any future use allows grouping such territories to the owning state for different display.

If you're happy with this suggestion, I can raise a PR

Edit: After reading more of the list and seeing a country such as Sint Marteen which is a constituent country of Netherlands, probably a more generic flag name is `part_of`

**Comment by necessarylion** [comment]
Hey @Skarvion, thanks a bunch for bringing this! I had no idea about this until today. Let’s use `part_of` and feel free to create a PR if you’d like!
